const BOOKINGS_PERMS = {
    CREATE_BOOKINGS: {
        PERMITTED_ROLES: ["STAFF", "MANAGER"],
        PERMITTED_POLICIES: ["CREATE_BOOKING"]
    },
    READ_BOOKINGS: {
        PERMITTED_ROLES: ["STAFF", "MANAGER"],
        PERMITTED_POLICIES: ["READ_BOOKINGS"]
    },
    DELETE_BOOKINGS: {
        PERMITTED_ROLES: ["MANAGER"],
        PERMITTED_POLICIES: []
    }
};

module.exports = BOOKINGS_PERMS;